# Generated by Django 3.0.7 on 2020-06-16 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0004_post_history'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post_history',
        ),
    ]
