# Generated by Django 3.0.6 on 2020-06-23 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0009_remove_post_reported_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='times_reported',
            field=models.IntegerField(default=0),
        ),
    ]
