# Generated by Django 3.0.6 on 2020-06-23 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0011_post_reported_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='times_reported',
        ),
    ]
