# Generated by Django 3.0.6 on 2020-06-23 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_report'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Report',
        ),
    ]
